onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group Utilization -color {Cornflower Blue} -format Analog-Step -height 84 -max 1024.0 -radix unsigned /mempool_tb/snitch_utilization
add wave -noupdate -group Utilization /mempool_tb/instruction_handshake
add wave -noupdate -group Utilization -color {Cornflower Blue} -format Analog-Step -height 84 -max 1024.0 -radix unsigned /mempool_tb/lsu_utilization
add wave -noupdate -group Utilization /mempool_tb/lsu_handshake
add wave -noupdate -group Utilization -color {Cornflower Blue} -format Analog-Step -height 84 -max 1024.0 -radix unsigned /mempool_tb/lsu_pressure
add wave -noupdate -group Utilization /mempool_tb/lsu_request
add wave -noupdate -group Utilization -color {Cornflower Blue} -format Analog-Step -height 84 -max 1024.0 -radix unsigned /mempool_tb/gen_utilization/dspu_utilization
add wave -noupdate -group Utilization /mempool_tb/gen_utilization/dspu_handshake
add wave -noupdate -group Utilization -color {Cornflower Blue} -format Analog-Step -height 84 -max 1024.0 -radix unsigned /mempool_tb/gen_utilization/mac_utilization
add wave -noupdate -group Utilization /mempool_tb/gen_utilization/dspu_mac
add wave -noupdate -group Utilization -color {Cornflower Blue} -format Analog-Step -height 84 -max 16.0 -radix unsigned /mempool_tb/axi_w_utilization
add wave -noupdate -group Utilization -color {Cornflower Blue} -format Analog-Step -height 84 -max 16.0 -radix unsigned /mempool_tb/axi_r_utilization
add wave -noupdate /mempool_tb/wfi
add wave -noupdate -group {core[0][0][0][0]} -group Params {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/BootAddr}
add wave -noupdate -group {core[0][0][0][0]} -group Params {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/MTVEC}
add wave -noupdate -group {core[0][0][0][0]} -group Params {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/RVE}
add wave -noupdate -group {core[0][0][0][0]} -group Params {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/RVM}
add wave -noupdate -group {core[0][0][0][0]} -group Params {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/RegisterOffloadReq}
add wave -noupdate -group {core[0][0][0][0]} -group Params {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/RegisterOffloadResp}
add wave -noupdate -group {core[0][0][0][0]} -group Params {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/RegisterTCDMReq}
add wave -noupdate -group {core[0][0][0][0]} -group Params {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/RegisterTCDMResp}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/clk_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/rst_i}
add wave -noupdate -group {core[0][0][0][0]} -radix unsigned {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/hart_id_i}
add wave -noupdate -group {core[0][0][0][0]} -divider Instructions
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/inst_addr_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/inst_data_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/inst_valid_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/inst_ready_i}
add wave -noupdate -group {core[0][0][0][0]} -divider Load/Store
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_qaddr_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_qwrite_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_qamo_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_qdata_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_qstrb_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_qvalid_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_qready_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_pdata_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_perror_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_pvalid_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/data_pready_o}
add wave -noupdate -group {core[0][0][0][0]} -divider Accelerator
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_qaddr_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_qid_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_qdata_op_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_qdata_arga_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_qdata_argb_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_qdata_argc_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_qvalid_o}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_qready_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_pdata_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_pid_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_perror_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_pvalid_i}
add wave -noupdate -group {core[0][0][0][0]} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_pready_o}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/illegal_inst}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/stall}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/lsu_stall}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_stall}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/zero_lsb}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/pc_d}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/pc_q}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/wfi_d}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/wfi_q}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/wake_up_sync_i}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/wake_up_d}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/wake_up_q}
add wave -noupdate -group {core[0][0][0][0]} -group Internal -divider LSU
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/ls_size}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/ls_amo}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/ld_result}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/lsu_qready}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/lsu_qvalid}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/lsu_pvalid}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/lsu_pready}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/lsu_rd}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/retire_load}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/retire_i}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/retire_acc}
add wave -noupdate -group {core[0][0][0][0]} -group Internal -divider Register
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/i_snitch_regfile/raddr_i}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/i_snitch_regfile/waddr_i}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/i_snitch_regfile/wdata_i}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/i_snitch_regfile/we_i}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/i_snitch_regfile/rdata_o}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/i_snitch_regfile/mem}
add wave -noupdate -group {core[0][0][0][0]} -group Internal -divider ALU
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/opa}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/opb}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/iimm}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/uimm}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/jimm}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/bimm}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/simm}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/adder_result}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/alu_result}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/rd}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/rs1}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/rs2}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/gpr_raddr}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/gpr_rdata}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/gpr_waddr}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/gpr_wdata}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/gpr_we}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/consec_pc}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/sb_d}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/sb_q}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/is_load}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/is_store}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/is_signed}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/is_fp_load}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/is_fp_store}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/ls_misaligned}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/ld_addr_misaligned}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/st_addr_misaligned}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/valid_instr}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/exception}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/alu_op}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/opa_select}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/opb_select}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/write_rd}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/uses_rd}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/next_pc}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/rd_select}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/rd_bypass}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/is_branch}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/csr_rvalue}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/csr_en}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/cycle_q}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/instret_q}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/acc_register_rd}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/operands_ready}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/dst_ready}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/opa_ready}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/opb_ready}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/shift_opa}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/shift_opa_reversed}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/shift_right_result}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/shift_left_result}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/shift_opa_ext}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/shift_right_result_ext}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/shift_left}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/shift_arithmetic}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/alu_opa}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/alu_opb}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/alu_writeback}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/csr_trace_q}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/csr_trace_en}
add wave -noupdate -group {core[0][0][0][0]} -group Internal {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/gen_cores[0]/gen_mempool_cc/riscv_core/i_snitch/core_events_o}
add wave -noupdate -expand -subitemconfig {{/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_master_req_o[1].wdata} -expand {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_master_req_o[0].wdata} -expand} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_master_req_o}
add wave -noupdate -group SG0 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG0 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG0 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG0 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG0 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG0 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG0 -subitemconfig {{/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[0].wdata} -expand} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG1 -subitemconfig {{/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i[1]} -expand {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i[1].wdata} -expand} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG2 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG2 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG2 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG2 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG2 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG2 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG2 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG2 -subitemconfig {{/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[2]} -expand {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[2].wdata} -expand} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group SG3 -subitemconfig {{/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[3]} -expand {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[3].wdata} -expand} {/mempool_tb/dut/i_mempool_cluster/gen_groups[0]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 -subitemconfig {{/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[4]} -expand {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[4].wdata} -expand} {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G1SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[1]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG0-1 -subitemconfig {{/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[5]} -expand {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[5].wdata} -expand} {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G2SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[2]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[0]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG0-1 -subitemconfig {{/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[6]} -expand {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[6].wdata} -expand {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[0].wdata} -expand} {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[1]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[2]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[0]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[1]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[2]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[3]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[4]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[5]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[6]/i_tile/tcdm_slave_req_i}
add wave -noupdate -group G3SG2-3 -subitemconfig {{/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[6]} -expand {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i[6].wdata} -expand} {/mempool_tb/dut/i_mempool_cluster/gen_groups[3]/gen_rtl_group/i_group/gen_sub_groups[3]/gen_rtl_sg/i_sub_group/gen_tiles[7]/i_tile/tcdm_slave_req_i}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {382801351 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {160740528 ps} {402891551 ps}
